# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

# resources:
# - repo: self

resources:
  repositories:
  - repository: self
    type: github
    endpoint: github.com_g1soori
  - repository: api
    type: github
    endpoint: g1soori

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd39e68ce-28c7-4392-bd41-cef9bd82398b'
  imageRepository: 'hygieiaapi'
  containerRegistry: 'g1sooricontainerreg.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'g1sooricontainerreg1422c7ea-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Deploy
  displayName: Deploy stage
#  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'g1soorihygieiak8s-1362.hygieia'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          
          - checkout: self 
          - checkout: api   
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Build.SourcesDirectory)/hygieia-api-deploy.yaml
                $(Build.SourcesDirectory)/hygieia-api-svc.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

