apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-premium-mongo
  namespace: hygieia
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi