apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hygieiaapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hygieiaapi 
    spec:
      containers:
        - name: hygieiaapi 
          image: g1sooricontainerreg.azurecr.io/hygieiaapi
          ports:
          - containerPort: 80